### ISSUE TITLE
Container moves fail: "arrayUtilSvc is not defined"

### ISSUE THREAD

**Issue by klausw** [GoogleCloudPlatform/PerfKitExplorer#189]
This is on v25.2 - how to reproduce:

- open a dashboard with multiple containers
- select the 2nd container
- click the up arrow to move the container

Result: container doesn't move, JS console shows:

ReferenceError: arrayUtilSvc is not defined
    at p3rf.perfkit.explorer.components.container.ContainerService.movePrevious (https://cloud-health.googleplex.com/_static/25-2.387185299439384596/perfkit_scripts.js:259:120)
    at fn (eval at <anonymous> (https://cloud-health.googleplex.com/_static/25-2.387185299439384596/third_party/angular/angular.min.js:212:83), <anonymous>:4:346)
    at f (https://cloud-health.googleplex.com/_static/25-2.387185299439384596/third_party/angular/angular.min.js:252:74)

**Comment by klausw** [comment]
+@voellm
